import pandas as pd
import numpy as np

# We need to run this from the backend directory to have access to app.utils
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from app.utils.parser_utils import clean_dataframe

def test_smart_parser():
    print("--- Creating Messy DataFrame ---")
    
    # 3 rows of metadata
    # 1 empty row
    # Header row
    # Data rows
    data = [
        ["Report: Sales Data 2022-2023", np.nan, np.nan, np.nan, np.nan],
        ["Generated By: System", np.nan, np.nan, np.nan, np.nan],
        [np.nan, np.nan, np.nan, np.nan, np.nan],
        ["Region", "Revenue", "Profit", np.nan, "Salesperson"],
        ["North", 50000, 15000, np.nan, "Alice"],
        ["South", 60000, 18000, np.nan, "Bob"],
        [np.nan, np.nan, np.nan, np.nan, np.nan], # Empty row in data
        ["East", 45000, 12000, np.nan, "Charlie"],
    ]
    
    # Create the raw dataframe (pandas often reads unstructured excel like this)
    raw_df = pd.DataFrame(data, columns=["Unnamed: 0", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4"])
    
    print("RAW DF:")
    print(raw_df)
    
    print("\n--- Running clean_dataframe ---")
    clean_df = clean_dataframe(raw_df)
    
    print("CLEAN DF:")
    print(clean_df)

def test_json_flattener():
    from app.utils.parser_utils import flatten_json_to_df
    print("\n--- Testing JSON Flattener ---")
    data = [
        {"user": {"id": 1, "name": "Alice"}, "city": "NYC", "purchases": [1, 2]},
        {"user": {"id": 2, "name": "Bob"}, "city": "LA", "purchases": [3]}
    ]
    df = flatten_json_to_df(data)
    print(df)

if __name__ == "__main__":
    test_smart_parser()
    test_json_flattener()
