"""
Pydantic schemas for query-related API requests and responses.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class QueryRequest(BaseModel):
    """POST /query — natural language question from the user."""

    question: str
    dataset_id: Optional[str] = None  # optional: target a specific dataset


class StructuredIntent(BaseModel):
    """
    The intermediate representation between NL question and SQL.

    Generated by the LLM adapter — NEVER contains raw data.
    """

    metric: str  # e.g. "revenue", "profit"
    dimension: Optional[str] = None  # e.g. "region", "month"
    filters: List[Dict[str, Any]] = []  # e.g. [{"column": "region", "op": "=", "value": "East"}]
    time_range: Optional[str] = None  # e.g. "last 6 months"
    table_name: Optional[str] = None


class SummaryCard(BaseModel):
    title: str
    value: str
    description: str

class KPICard(BaseModel):
    title: str
    value: Any
    description: str

class Chart(BaseModel):
    type: str
    x_axis: Optional[str] = None
    y_axis: Optional[str] = None
    series: Optional[str] = None
    reason: str

class InsightPanel(BaseModel):
    type: str
    text: str

class Anomaly(BaseModel):
    text: str
    severity: str

class DashboardResponse(BaseModel):
    summary_card: SummaryCard
    kpi_cards: List[KPICard] = []
    chart: Optional[Chart] = None
    insights_panel: List[InsightPanel] = []
    anomalies: List[Anomaly] = []


class QueryResponse(BaseModel):
    """POST /query response with results and transparency info."""

    data: List[Dict[str, Any]]
    sql: str  # the validated/rewritten SQL that was actually executed
    chart_hint: Optional[str] = None  # e.g. "bar", "line", "pie"
    row_count: int = 0
    # Optional warnings (e.g. fuzzy column correction notices)
    warnings: List[str] = []
    # Available fields in the dataset (populated on validation errors or when empty results)
    available_fields: Optional[List[str]] = None
    # execution profile mappings
    execution_plan: Optional[Dict[str, Any]] = None
    explanation: Optional[Dict[str, Any]] = None
    insights: Optional[DashboardResponse] = None


class AsyncJobResponse(BaseModel):
    """Returned when a query is dispatched to the background (V4)."""
    job_id: str
    status: str
    message: str


class SchemaHintResponse(BaseModel):
    """
    Returned when a query fails due to an unknown column.
    Provides friendly guidance instead of a raw error.
    """
    error: str
    did_you_mean: Optional[str] = None
    available_columns: List[str] = []
    inferred_metrics: List[str] = []
    tip: str = ""
